import Menu from "../componetes/menu"
import "./css/base.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Menu/>
          <header>
            <main>
              {children}
            </main>
            <footer>
              <p>LPR II 2025</p>
            </footer>
          </header>
        </body>
    </html>
  )
}